services:
  mariadb:
    image: mariadb:latest
    container_name: dj-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --max-connections=1000
    restart: unless-stopped

  domserver:
    image: domjudge/domserver:${DOMJUDGE_VERSION}
    container_name: domserver
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - CONTAINER_TIMEZONE=${TZ}
      - JUDGEDAEMON_PASSWORD=${JUDGEDAEMON_PASSWORD}
    ports:
      - "${DOMSERVER_PORT}:80"
    depends_on:
      - mariadb
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    restart: unless-stopped

volumes:
  mariadb_data:
